#!/bin/bash
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

echo ""

echo "Running stampzilla installer"
./stampzilla/install

echo -n "Creating symbolic links..."
ln -sf `pwd`/usr/bin/collision /usr/bin/
ln -sf `pwd`/usr/share/collision/ /usr/share/
ln -sf `pwd`/usr/lib/collision/ /usr/lib/
echo "done"

echo ""
echo "All done, have fun!";
