ARDUINO_DIR = /usr/share/arduino/

TARGET       = XbeeShield.cpp
BOARD_TAG    = atmega328
ARDUINO_PORT = /dev/ttyUSB0

MCU          = atmega328
AVR_MCU      = m328p
F_CPU        = 16000000

AVRDUDE_ARD_PROGRAMMER = stk500v1
AVRDUDE_ARD_BAUDRATE = 57600

#ARDUINO_LIBS = Xbee

#ard-parse-boards --boards

include /usr/share/arduino/Arduino.mk
